"""new_table_video

Revision ID: 2decc18d29cd
Revises: a69d57f8808c
Create Date: 2025-12-24 14:45:51.020710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2decc18d29cd'
down_revision: Union[str, Sequence[str], None] = 'a69d57f8808c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='视频唯一标识符'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='视频标题'),
    sa.Column('type', sa.String(length=100), nullable=True, comment='视频类型分类：电影/电视剧/动漫/短剧等'),
    sa.Column('cover_url', sa.Text(), nullable=True, comment='封面图片URL地址'),
    sa.Column('description', sa.Text(), nullable=True, comment='视频简短描述'),
    sa.Column('episode_count', sa.Integer(), nullable=True, comment='视频总集数（除电影外几乎都有）'),
    sa.Column('actors', sa.Text(), nullable=True, comment='演员列表，多个演员用逗号分隔，动漫则为声优'),
    sa.Column('year', sa.Integer(), nullable=True, comment='上映年份'),
    sa.Column('baidu_url', sa.Text(), nullable=True, comment='百度网盘资源链接'),
    sa.Column('quark_url', sa.Text(), nullable=True, comment='夸克网盘资源链接'),
    sa.Column('other_cloud_url', sa.Text(), nullable=True, comment='其他云盘资源链接'),
    sa.Column('url_status', sa.Integer(), nullable=False, comment='网盘链接状态 0都失效,1主流 (百度/夸克) 有效,2 other盘有效,3都有效'),
    sa.Column('marketing_text', sa.Text(), nullable=True, comment='营销文本：闲鱼等平台推广文本'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，用于软删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_created_at'), 'videos', ['created_at'], unique=False)
    op.create_index(op.f('ix_videos_deleted_at'), 'videos', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.create_index(op.f('ix_videos_title'), 'videos', ['title'], unique=False)
    op.create_index(op.f('ix_videos_type'), 'videos', ['type'], unique=False)
    op.create_index(op.f('ix_videos_updated_at'), 'videos', ['updated_at'], unique=False)
    op.create_index(op.f('ix_videos_url_status'), 'videos', ['url_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_url_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_updated_at'), table_name='videos')
    op.drop_index(op.f('ix_videos_type'), table_name='videos')
    op.drop_index(op.f('ix_videos_title'), table_name='videos')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_deleted_at'), table_name='videos')
    op.drop_index(op.f('ix_videos_created_at'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
