"""new_JSONB_video_extra_params

Revision ID: 427a74fc497f
Revises: 2decc18d29cd
Create Date: 2025-12-24 15:21:15.376498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '427a74fc497f'
down_revision: Union[str, Sequence[str], None] = '2decc18d29cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('extra_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='额外参数：JSON格式存储其他相关信息'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'extra_params')
    # ### end Alembic commands ###
