"""new_video_arg_rating

Revision ID: 8ca8565a7af8
Revises: 427a74fc497f
Create Date: 2025-12-24 15:42:03.451673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca8565a7af8'
down_revision: Union[str, Sequence[str], None] = '427a74fc497f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('rating', sa.NUMERIC(precision=3, scale=1), nullable=True, comment='视频评分'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'rating')
    # ### end Alembic commands ###
