"""new_col_status

Revision ID: a33ea5c045f4
Revises: f500f362d28f
Create Date: 2026-01-26 17:18:05.336778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33ea5c045f4'
down_revision: Union[str, Sequence[str], None] = 'f500f362d28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('sale_status', sa.Integer(), nullable=True, comment='视频上架状态 0未上架,1已上架'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'sale_status')
    # ### end Alembic commands ###
