"""new_col_hot

Revision ID: b283de174e48
Revises: e1db10db04a7
Create Date: 2026-01-26 11:51:01.164996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b283de174e48'
down_revision: Union[str, Sequence[str], None] = 'e1db10db04a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_dramas_created_at'), table_name='short_dramas')
    op.drop_index(op.f('ix_short_dramas_deleted_at'), table_name='short_dramas')
    op.drop_index(op.f('ix_short_dramas_id'), table_name='short_dramas')
    op.drop_index(op.f('ix_short_dramas_title'), table_name='short_dramas')
    op.drop_index(op.f('ix_short_dramas_type'), table_name='short_dramas')
    op.drop_index(op.f('ix_short_dramas_updated_at'), table_name='short_dramas')
    op.drop_index(op.f('ix_short_dramas_url_status'), table_name='short_dramas')
    op.drop_table('short_dramas')
    op.add_column('videos', sa.Column('hot_score', sa.Integer(), nullable=True, comment='视频热门度评分'))
    op.add_column('videos', sa.Column('hot_reason', sa.Text(), nullable=True, comment='视频热门度评分原因'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'hot_reason')
    op.drop_column('videos', 'hot_score')
    op.create_table('short_dramas',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='短剧唯一标识符'),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='短剧标题'),
    sa.Column('subtitle', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='短剧副标题'),
    sa.Column('cover_url', sa.TEXT(), autoincrement=False, nullable=True, comment='封面图片URL地址'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='短剧详细描述'),
    sa.Column('episode_count', sa.INTEGER(), autoincrement=False, nullable=True, comment='短剧总集数'),
    sa.Column('actors', sa.TEXT(), autoincrement=False, nullable=True, comment='演员列表，多个演员用逗号分隔'),
    sa.Column('publish_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='发布日期，字符串格式'),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='短剧类型分类'),
    sa.Column('baidu_url', sa.TEXT(), autoincrement=False, nullable=True, comment='百度网盘资源链接'),
    sa.Column('quark_url', sa.TEXT(), autoincrement=False, nullable=True, comment='夸克网盘资源链接'),
    sa.Column('other_cloud_url', sa.TEXT(), autoincrement=False, nullable=True, comment='其他云盘资源链接'),
    sa.Column('url_status', sa.INTEGER(), autoincrement=False, nullable=False, comment='网盘链接状态 0都失效,1主流 (百度/夸克) 有效,2 other盘有效,3都有效'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='最后更新时间'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='删除时间，用于软删除'),
    sa.Column('marketing_text', sa.TEXT(), autoincrement=False, nullable=True, comment='营销文本'),
    sa.PrimaryKeyConstraint('id', name=op.f('short_dramas_pkey'))
    )
    op.create_index(op.f('ix_short_dramas_url_status'), 'short_dramas', ['url_status'], unique=False)
    op.create_index(op.f('ix_short_dramas_updated_at'), 'short_dramas', ['updated_at'], unique=False)
    op.create_index(op.f('ix_short_dramas_type'), 'short_dramas', ['type'], unique=False)
    op.create_index(op.f('ix_short_dramas_title'), 'short_dramas', ['title'], unique=False)
    op.create_index(op.f('ix_short_dramas_id'), 'short_dramas', ['id'], unique=False)
    op.create_index(op.f('ix_short_dramas_deleted_at'), 'short_dramas', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_short_dramas_created_at'), 'short_dramas', ['created_at'], unique=False)
    # ### end Alembic commands ###
