"""short_drama

Revision ID: bbef4565159b
Revises: d04f574eac81
Create Date: 2025-08-21 19:35:56.675311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbef4565159b'
down_revision: Union[str, Sequence[str], None] = 'd04f574eac81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_dramas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='短剧唯一标识符'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='短剧标题'),
    sa.Column('subtitle', sa.String(length=255), nullable=True, comment='短剧副标题'),
    sa.Column('cover_url', sa.Text(), nullable=True, comment='封面图片URL地址'),
    sa.Column('description', sa.Text(), nullable=True, comment='短剧详细描述'),
    sa.Column('episode_count', sa.Integer(), nullable=True, comment='短剧总集数'),
    sa.Column('actors', sa.Text(), nullable=True, comment='演员列表，多个演员用逗号分隔'),
    sa.Column('publish_date', sa.String(length=50), nullable=True, comment='发布日期，字符串格式'),
    sa.Column('type', sa.String(length=100), nullable=True, comment='短剧类型分类'),
    sa.Column('baidu_url', sa.Text(), nullable=True, comment='百度网盘资源链接'),
    sa.Column('quark_url', sa.Text(), nullable=True, comment='夸克网盘资源链接'),
    sa.Column('other_cloud_url', sa.Text(), nullable=True, comment='其他云盘资源链接'),
    sa.Column('url_status', sa.Integer(), nullable=False, comment='网盘链接状态 0都失效,1主流 (百度/夸克) 有效,2 other盘有效,3都有效'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，用于软删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_dramas_created_at'), 'short_dramas', ['created_at'], unique=False)
    op.create_index(op.f('ix_short_dramas_deleted_at'), 'short_dramas', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_short_dramas_id'), 'short_dramas', ['id'], unique=False)
    op.create_index(op.f('ix_short_dramas_title'), 'short_dramas', ['title'], unique=False)
    op.create_index(op.f('ix_short_dramas_type'), 'short_dramas', ['type'], unique=False)
    op.create_index(op.f('ix_short_dramas_updated_at'), 'short_dramas', ['updated_at'], unique=False)
    op.create_index(op.f('ix_short_dramas_url_status'), 'short_dramas', ['url_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_dramas_url_status'), table_name='short_dramas')
    op.drop_index(op.f('ix_short_dramas_updated_at'), table_name='short_dramas')
    op.drop_index(op.f('ix_short_dramas_type'), table_name='short_dramas')
    op.drop_index(op.f('ix_short_dramas_title'), table_name='short_dramas')
    op.drop_index(op.f('ix_short_dramas_id'), table_name='short_dramas')
    op.drop_index(op.f('ix_short_dramas_deleted_at'), table_name='short_dramas')
    op.drop_index(op.f('ix_short_dramas_created_at'), table_name='short_dramas')
    op.drop_table('short_dramas')
    # ### end Alembic commands ###
