"""api_token

Revision ID: d04f574eac81
Revises: 
Create Date: 2025-08-21 11:22:15.795613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04f574eac81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='API Token唯一标识符'),
    sa.Column('hashed_token', sa.String(length=64), nullable=False, comment='API Token哈希值，用于验证'),
    sa.Column('is_valid', sa.Boolean(), nullable=False, comment='Token是否有效，True为有效，False为无效'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Token创建时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Token删除时间，用于软删除'),
    sa.Column('note', sa.Text(), nullable=True, comment='Token备注信息，用于描述Token用途或其他说明'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_token')
    )
    op.create_index(op.f('ix_api_tokens_created_at'), 'api_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_tokens_deleted_at'), 'api_tokens', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_api_tokens_id'), 'api_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_api_tokens_is_valid'), 'api_tokens', ['is_valid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_tokens_is_valid'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_deleted_at'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_created_at'), table_name='api_tokens')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
