"""new_col_hot_tag

Revision ID: d5479788efe9
Revises: a33ea5c045f4
Create Date: 2026-01-26 18:32:15.522388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5479788efe9'
down_revision: Union[str, Sequence[str], None] = 'a33ea5c045f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('hot_tags', sa.String(length=255), nullable=True, comment='视频热门度标签，逗号分隔'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'hot_tags')
    # ### end Alembic commands ###
