"""new_col_region

Revision ID: df2248d3139e
Revises: b283de174e48
Create Date: 2026-01-26 16:26:10.437461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df2248d3139e'
down_revision: Union[str, Sequence[str], None] = 'b283de174e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('region', sa.String(length=100), nullable=True, comment='视频主要受众，如美剧/韩剧/日剧等'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'region')
    # ### end Alembic commands ###
