"""new_video_arg_quality_tag

Revision ID: e1db10db04a7
Revises: 8ca8565a7af8
Create Date: 2025-12-24 16:31:31.776220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1db10db04a7'
down_revision: Union[str, Sequence[str], None] = '8ca8565a7af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('quality_tag', sa.String(length=100), nullable=True, comment='视频质量标签：不仅包含1080P/720P/480P，还有WEB-DL等标签'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'quality_tag')
    # ### end Alembic commands ###
