"""new_col_finished_1

Revision ID: f500f362d28f
Revises: df2248d3139e
Create Date: 2026-01-26 16:53:24.018456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f500f362d28f'
down_revision: Union[str, Sequence[str], None] = 'df2248d3139e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('finished', sa.Integer(), nullable=True, comment='视频是否完结 0连载中,1已完结'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'finished')
    # ### end Alembic commands ###
